# Missing values

```{r}
library(tidyverse)
library(readr)
```


# Load data and replace \N with NA
```{r}
basic <- read_tsv("data/name.basic.tsv")
basic$nconst <- gsub("\\N",NA,basic$nconst,fix=TRUE)
basic$primaryName <- gsub("\\N",NA,basic$primaryName,fix=TRUE)
basic$birthYear <- gsub("\\N",NA,basic$birthYear,fix=TRUE)
basic$deathYear<- gsub("\\N",NA,basic$deathYear,fix=TRUE)
basic$primaryProfession <- gsub("\\N",NA,basic$primaryProfession,fix=TRUE)
basic$knownForTitles <- gsub("\\N",NA,basic$knownForTitles,fix=TRUE)
colSums(is.na(basic)) %>%
  sort(decreasing = TRUE)
rowSums(is.na(basic)) %>%
  sort(decreasing = TRUE)
```


## Show the graph of missing data
```{r}
source("scripts/visna.R")
visna(basic)
visna(basic,percent=TRUE)
```

From the graph, it is obvious that no missing values in tconst, and almost no missing values in Primary Name. 
The birth year and death year are having the largest amount of missing values maybe because it is hard to get the specific birth and death time. 

